update_climate:
  description: Change the hvac mode of the given climate device.
  fields:
    enitity_id:
      description: The climates enitity_id
      example: climate.livingroom
    windows:
      description: The climate will be off when one of these sensors is on.
      example:
        [binary_sensor.livingroom_window, binary_sensor.livingroom_balcony door]
    sensors_off:
      description: The climate will be off when one of these sensors is off.
      example:
        [binary_sensor.climate_on, binary_sensor.livingroom_climate_on]
    sensor_presence:
      description: The climate will switch to active mode if this sensor is on.
      example: binary_sensor.someone_at_home
    heating_from_hour:
      description: Start time from which heating is to start
      example: 8
    heating_to_hour:
      description: End time to which the heating is to last.
      example: 17
